# Generated by Django 5.2.11 on 2026-03-05 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0004_announcementmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
